#настройка высоты и скорости - можно указывать как целые так и рациональные пример : 2.3
speed: 3.8 #Скорость
height: 1  #Высота

#Настройка блока(ов)
material:
  mat: BEACON #Блок при наступление на него будет выполнен прыжок
  name: Маяк #Имя блока (Имя блоку нужно дать через наковальню , иначе плагин работать не будет
             # это сделно что-бы было не на все блоки 'mat' распространялся прыжок!)
